# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               madelyne z. xiao
tagline:             
description:         occasionally writing, often reading, always thinking. Made by <a href="https://twitter.com/madxiaodisease" target="_blank">@madxiaodisease</a>.'
url:                 http://cargocollective.com/madelynex
baseurl:             '/home'
paginate:            5

# About/contact
author:
  name:              Madelyne Xiao
  url:               https://twitter.com/madxiaodisease
  email:             madelyne.xiao96@gmail.com

# Custom vars
version:             1.0.0`
